Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,6 +52,10 @@ jobs:
             - name: Upload DevBuild as release
               if: github.repository == 'PhasedGapple/HackMee-Vencord'
               run: |
+                  if ! gh release view devbuild; then
+                    echo "Release not found. Creating release."
+                    gh release create devbuild --title "DevBuild $RELEASE_TAG" --notes "Minor DevBuild"
+                  fi
                   gh release upload devbuild --clobber dist/*
                   gh release edit devbuild --title "DevBuild $RELEASE_TAG"
               env:
